tags:
  - name: user
    description: Работа с пользователем
  - name: operations
    description: Работа с операциями
  - name: categories
    description: Работа с категориями
components:
  securitySchemes: {
    bearerAuth: {
      type: 'http',
      scheme: 'bearer',
      description: 'Pass {token} to Value input',
      bearerFormat: 'JWT',
    }
  }
  schemas:
    User:
      type: object
      title: User
      required:
        - email
        - password
      exapmle:
        _id: '123'
        email: 'email@email.ru'
        password: 'password'
      properties:
        _id:
          description: 'id пользователя, генерируется автоматически'
          type: string
        email:
          type: string
          description: 'Email пользователя'
        token:
          type: string
          description: 'Токен пользователя'
    Operation:
      type: object
      title: Operation
      required:
        - value
        - type
      exapmle:
        _id: '123123'
        title: 'Заголовок'
      properties:
        _id:
          description: 'id операции, генерируется автоматически'
          type: string
        title:
          type: string
          description: 'Заголовок операции'
        description:
          type: string
          description: 'Описание операции'
        value:
          description: 'Сумма (всегда положительная)'
          type: number
        type:
          type: string
          enum:
            - income
            - expense
          description: 'Тип операции (income - доход, expense - расход)'
        category:
          description: 'объект категории с _id'
          type: object
        date:
          type: string
          format: date-time
          description: 'Дата списания'
          default: 'Текущее время'
        repetitive:
          type: boolean
          description: 'Флаг повторяемости операции'
          default: false
        repetitiveDay:
          type: number
          description: 'День для повторения операции'
          default: 1
        deletedDate:
          type: string
          format: date-time
          description: 'Дата удаления операции'
        updatedAt:
          type: string
          format: date-time
          description: 'Дата редактирования операции'
        createdAt:
          type: string
          format: date-time
          description: 'Дата создания операции'
    Category:
      type: object
      title: Category
      required:
        - title
      exapmle:
        _id: '123'
        title: 'Название категории'
      properties:
        _id:
          description: 'id категории, генерируется автоматически'
          type: string
        title:
          type: string
          description: 'Название категории'
        deletedDate:
          type: string
          format: date-time
          description: 'Дата удаления категории'
        updatedAt:
          type: string
          format: date-time
          description: 'Дата редактирования категории'
        createdAt:
          type: string
          format: date-time
          description: 'Дата создания категории'
  requestBodies:
    User:
      required: true
      content:
        application/json:
          schema:
            required:
              - email
              - password
            properties:
              email:
                type: string
              password:
                type: string
    UserReg:
      required: true
      content:
        application/json:
          schema:
            required:
              - email
              - password
              - password2
            properties:
              email:
                type: string
              password:
                type: string
              password2:
                type: string
    Operation:
      required: true
      content:
        application/json:
          schema:
            type: object
            title: Operation
            required:
              - value
              - type
            properties:
              value:
                type: number
              type:
                type: string
                enum:
                  - income
                  - expense
              title:
                type: string
              description:
                type: string
              category:
                type: object
              date:
                type: string
                format: date-time
              repetitive:
                type: boolean
              repetitiveDay:
                type: number
    Category:
      required: true
      content:
        application/json:
          schema:
            type: object
            title: Operation
            required:
              - title
            properties:
              title:
                type: string
paths: {}
